### PR TITLE
Adding support for pids local to current working directory.

### PR DESCRIPTION
**Pull request by jmervine**
Tests are passing.

### CODE REVIEW

**Comment by jmervine** [comment]
Hey, I wanted to check and see if there's anyway this will ever be merged. I would really rather not created a new NPM fork, but am using this a production application and prefer not continue deploying via git. Thanks!

**Comment by js-seth-h** [comment]
Thank you for contribution.

**Comment by jmervine** [comment]
My pleasure! Mind letting me know when a new npm is pushed?

**Comment by js-seth-h** [comment]
Just Now, I publish 0.3.3 that include option.local.

2015-03-02 18:08 GMT+09:00 Joshua Mervine notifications@github.com:

**Comment by jmervine** [comment]
Awesome, thanks!

**Pull request merged**
